/** 共享数据集：常见英文名（全小写）。供 bigram / MLP 嵌入 / 激活健康等模块使用 */
export const NAMES: string[] = Array.from(
  new Set([
    // ---- 常见女名 ----
    "emma", "olivia", "ava", "isabella", "sophia", "charlotte", "mia", "amelia", "harper", "evelyn",
    "abigail", "emily", "elizabeth", "mila", "ella", "avery", "sofia", "camila", "aria", "scarlett",
    "victoria", "madison", "luna", "grace", "chloe", "penelope", "layla", "riley", "zoey", "nora",
    "lily", "eleanor", "hannah", "lillian", "addison", "aubrey", "ellie", "stella", "natalie", "zoe",
    "leah", "hazel", "violet", "aurora", "savannah", "audrey", "brooklyn", "bella", "claire", "skylar",
    "lucy", "paisley", "everly", "anna", "caroline", "nova", "genesis", "emilia", "kennedy", "samantha",
    "maya", "willow", "kinsley", "naomi", "aaliyah", "elena", "sarah", "ariana", "allison", "gabriella",
    "alice", "madelyn", "cora", "ruby", "eva", "serenity", "autumn", "adeline", "hailey", "gianna",
    "valentina", "isla", "eliana", "quinn", "nevaeh", "ivy", "sadie", "piper", "lydia", "alexa",
    "josephine", "emery", "julia", "delilah", "arianna", "vivian", "kaylee", "sophie", "brielle", "madeline",
    "peyton", "rylee", "clara", "hadley", "melanie", "mackenzie", "reagan", "adalynn", "liliana", "aubree",
    "jade", "katherine", "isabelle", "natalia", "raelynn", "maria", "athena", "ximena", "arya", "leilani",
    "taylor", "faith", "rose", "kylie", "alexandra", "mary", "margaret", "lyla", "ashley", "amaya",
    "eliza", "brianna", "bailey", "andrea", "khloe", "jasmine", "melody", "iris", "isabel", "norah",
    "annabelle", "valeria", "emerson", "adalyn", "ryleigh", "eden", "emersyn", "anastasia", "kayla", "alyssa",
    "juliana", "charlie", "esther", "ariel", "cecilia", "valerie", "alina", "molly", "reese", "aliyah",
    "lilly", "parker", "finley", "morgan", "sydney", "jordyn", "eloise", "trinity", "daisy", "kimberly",
    "lauren", "genevieve", "sara", "arabella", "harmony", "elise", "remi", "teagan", "alexis", "london",
    "sloane", "laila", "lucia", "diana", "juliette", "sienna", "elliana", "londyn", "ayla", "callie",
    "gracie", "josie", "amara", "jocelyn", "angela", "ana", "daniela", "paris", "camille", "adelaide",
    "dakota", "wren", "alana", "esme", "gemma", "blake", "harlow", "june", "freya", "vera",
    "joanna", "phoebe", "nina", "tessa", "heidi", "camryn", "kate", "fiona", "georgia", "catalina",
    "hope", "gwendolyn", "jane", "mckenna", "cassidy", "virginia", "evangeline", "olive", "alani", "selena",
    "kaia", "phoenix", "joy", "celeste", "ophelia", "dahlia", "holly", "miriam", "cheyenne", "michelle",
    "angelina", "carmen", "adrianna", "kali", "lola", "celine", "mabel", "ainsley", "rachel", "dorothy",
    "rebecca", "edith", "lena", "jessica", "laura", "susan", "karen", "linda", "nancy", "donna",
    "carol", "sandra", "ruth", "sharon", "cynthia", "kathleen", "amy", "shirley", "helen", "deborah",
    "pamela", "debra", "stephanie", "carolyn", "christine", "janet", "maureen", "diane", "julie", "joyce",
    "heather", "teresa", "doris", "gloria", "jean", "cheryl", "mildred", "frances", "martha", "irene",
    // ---- 常见男名 ----
    "liam", "noah", "oliver", "elijah", "james", "william", "benjamin", "lucas", "henry", "theodore",
    "jack", "levi", "alexander", "jackson", "mateo", "daniel", "michael", "mason", "sebastian", "ethan",
    "logan", "owen", "samuel", "jacob", "asher", "aiden", "john", "joseph", "wyatt", "david",
    "leo", "luke", "julian", "hudson", "grayson", "matthew", "ezra", "gabriel", "carter", "isaac",
    "jayden", "luca", "anthony", "dylan", "lincoln", "thomas", "maverick", "elias", "josiah", "charles",
    "caleb", "christopher", "ezekiel", "miles", "jaxon", "isaiah", "andrew", "joshua", "nathan", "nolan",
    "adrian", "cameron", "santiago", "eli", "aaron", "ryan", "angel", "cooper", "waylon", "easton",
    "kai", "christian", "landon", "colton", "roman", "axel", "brooks", "jonathan", "robert", "jameson",
    "ian", "everett", "greyson", "wesley", "jeremiah", "hunter", "leonardo", "jordan", "jose", "bennett",
    "silas", "nicholas", "beau", "weston", "austin", "connor", "carson", "dominic", "xavier", "jaxson",
    "jace", "emmett", "adam", "declan", "rowan", "micah", "kayden", "gael", "river", "ryder",
    "kingston", "damian", "sawyer", "luka", "evan", "vincent", "legend", "myles", "harrison", "august",
    "bryson", "amir", "giovanni", "chase", "diego", "milo", "jasper", "walker", "jason", "brayden",
    "cole", "nathaniel", "george", "lorenzo", "zion", "luis", "archer", "enzo", "jonah", "thiago",
    "theo", "ayden", "zachary", "calvin", "braxton", "ashton", "rhett", "atlas", "jude", "bentley",
    "carlos", "ryker", "adriel", "arthur", "ace", "tyler", "jayce", "max", "elliot", "graham",
    "kaiden", "maxwell", "juan", "dean", "matteo", "malachi", "ivan", "elliott", "jesus", "emiliano",
    "gavin", "maddox", "camden", "hayden", "leon", "antonio", "justin", "tucker", "brandon", "abel",
    "judah", "finn", "king", "brody", "xander", "emmanuel", "barrett", "tristan", "brady", "kaleb",
    "preston", "oscar", "alejandro", "marcus", "alan", "joel", "victor", "abraham", "kaden", "edward",
    "grant", "eric", "patrick", "peter", "richard", "kevin", "steven", "mark", "paul", "kenneth",
    "timothy", "jeffrey", "scott", "brian", "frank", "gregory", "raymond", "dennis", "jerry", "walter",
    "terry", "gerald", "keith", "roger", "lawrence", "sean", "albert", "jesse", "willie", "bruce",
    "ralph", "roy", "eugene", "russell", "bobby", "philip", "harry", "howard", "fred", "alfred",
    "stanley", "ernest", "martin", "leroy", "tony", "mike", "danny", "carl", "clarence", "earl",
    "joe", "allen", "marvin", "glenn", "dale", "arnold", "harold", "norman", "warren", "chad",
    "kyle", "jared", "wayne", "billy", "corey", "derek", "trevor", "travis", "todd", "brent",
    "craig", "curtis", "darren", "dustin", "shawn", "shane", "troy", "marc", "neil", "ross",
    "drew", "colin", "spencer", "garrett", "mitchell", "clayton", "wade", "dallas", "chance", "dawson",
    "gunnar", "hank", "otto", "hugo", "felix", "cyrus", "ronan", "callum", "killian", "cormac",
    "desmond", "quentin", "reid", "sterling", "clark", "wilson", "ford", "reed", "wells", "banks",
    "hayes", "lane", "knox", "nash", "zane", "remy", "tate", "cash", "colt", "duke",
    "jax", "rex", "cruz", "kane", "seth", "noel", "ellis", "orion", "otis", "amos",
  ]),
);
